Первый коммит для спринта 13
qwerty-yhn/java-shareit pull request #1
Opened 2023-02-23 15:32 UTC by qwerty-yhn

2023-02-23 16:19 UTC, qwerty-yhn commented
Сергей привет!!)

2023-02-25 05:55 UTC, krylov-sergey-sergeevich requested changes
Привет

1) Можно лучше: в логах в контроллере желательно еще передавать краткий смысл того что делается, путь и метод это круто - но не совсем удобно как будто
2) Поправить везде исключения

Буду ждать с правками =)

2023-02-25 05:55 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/error/ErrorHandler.java
> +public class ErrorHandler {
А так и планировалось что во всех ErrorResponse первый эл-т пустая строка?)

2023-02-25 05:55 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            throw new NotFountException("object not exist");
какой объект? с каким айди не найден?

2023-02-25 05:55 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            throw new NotFountException("object not exist");
какой объект? с каким айди не найден?

2023-02-25 05:55 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            throw new NotFountException(" not valid Owner of object");
точно ли NotFountException это то исключение которое передает бизнес смысл происходящего?

2023-02-25 05:55 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +            throw new NotFountException("object not exist");
какой объект? с каким айди не найден?

2023-02-25 15:13 UTC, qwerty-yhn commented on src/main/java/ru/practicum/shareit/error/ErrorHandler.java
> +public class ErrorHandler {
Не это случайно, не всегда автоформатирование правит пробелы

2023-02-26 06:44 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

2023-03-05 16:20 UTC, merged