Первая отправка на ревью
qwerty-yhn/java-shareit pull request #2
Opened 2023-03-13 12:20 UTC by qwerty-yhn

Сергей добрый день! долго делал спринт, боролся с несколько дней с ошибкой, никто мне не смог помочь( пришлось заново переделывать задание. Хотел сделать через кастомный query но не нашел где бы я мог тестировать sql запросы, в итоге половину написал,  а потом затык и все...

2023-03-14 14:03 UTC, qwerty-yhn commented
Ааа... Ура, Я не могу в это поверить... Это просто издевательство какое-то, тесты постмана прохожу, а в гитхабе нет! Сергей, я очень торопился с проектом, а перед сдачей поменяли тесты гитхаба...и вообще капец, по пэкаджам не разделил, почему-то проект сразу ломался)

2023-03-15 17:00 UTC, krylov-sergey-sergeevich requested changes
Привет, поясни в каком статусе сейчас ситуация с проблемами с которыми ты столкнулся при разработке, чтобы я понимал и учитывал их.

Далее что поправить и улучшить:
1) Что отметил
2) Что значит "Плохое исключение" - это значит что надо создать специализированное исключение которое будет в себе передавать необходимую информацию, те если нет пользователя то оно скажет что нет пользователя с id = 14 например, если некорректный параметр исключение тоже скажет об этом, а не пустые строки это некорректно
3) Кое где задал вопросы просьба на нахи ответить

Буду ждать с правками, если что пиши в пачке =)

2023-03-15 17:00 UTC, krylov-sergey-sergeevich commented on pom.xml
> +			<artifactId>lombok-mapstruct-binding</artifactId>
Напомни для чего эта зависимость нам нужна?

2023-03-15 17:00 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                     @NotEmpty @RequestHeader("X-Sharer-User-Id") Long userId) {
"X-Sharer-User-Id" эта штука много где повторяется рекомендую ее вынести в класс Constants и использовать переменную

2023-03-15 17:00 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                 @RequestParam(defaultValue = "ALL", required = false) String state) {
Может ли state быть enum?

2023-03-15 17:00 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingDtoOut.java
> +public class BookingDtoOut {
BookingDtoOut  - немного странное название, что значит Out?

2023-03-15 17:00 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +@Service
На интерфейсе это не нужно

2023-03-15 17:00 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            throw new NotFoundException("");
Давай создадим специальное исключение BookingNotFoundException наследника NotFoundException и сделаем так чтобы каждый раз не повторять текст:
`() -> new BookingNotFoundException(bookingId));`

2023-03-15 17:00 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        userService.getUser(userId);
Мы это делаем для проверки что пользователь существует, я это понимаю, но тогда можно создать доп метод и назвать его соответствующе

2023-03-15 17:00 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            throw new NotFoundException("");
Плохое исключение

2023-03-15 17:00 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            throw new BadRequestException("");
Плохое исключение

2023-03-15 17:00 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            throw new BadRequestException("");
Плохое исключение

2023-03-15 17:00 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            throw new NotFoundException("");
Плохое исключение

2023-03-15 17:00 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            throw new BadRequestException("");
Плохое исключение

2023-03-15 17:00 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            throw new BadRequestException("");
Плохое исключение

2023-03-15 17:00 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            throw new NotFoundException("");
Плохое исключение

2023-03-15 17:00 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                .orElseThrow(() -> new NotFoundException("" + bookingId));
Плохое исключение, но с попыткой на что то хорошее

2023-03-15 17:00 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                throw new UnsupportedState(state);
Отлично

2023-03-15 17:00 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +@Service
Убрать

2023-03-15 17:00 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        return null;
что это?

2023-03-15 17:00 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            throw new NotFoundException(" not valid Owner(" + idOwner + ") of object");
Терпимо, но можно лучше

2023-03-15 17:00 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        return itemRepository.findById(idItem).orElseThrow(() -> new NotFoundException("Not found item = " + idItem));
Терпимо но можно лучше

2023-03-15 17:00 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            throw new BadRequestException("");
Плохое исключение

2023-03-15 17:00 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +@Service
Убрать

2023-03-15 17:00 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        List<User> usersTemp = getAllUsers();
Тут точно все хорошо?

2023-03-15 17:00 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +//        List<User> usersTemp = getAllUsers();
Тут точно все хорошо?

2023-03-15 17:00 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        User user = repository.findById(id).orElseThrow(() -> new NotFoundException(""));
Плохое исключение

2023-03-15 17:00 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +//    private void checkExist(User user) {
Почему закомментировано?

2023-03-15 17:00 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +    private User updateParameters(User user) {
Можно пояснить что этот метод делает? И почему мы достаем из бд все

2023-03-15 18:08 UTC, qwerty-yhn commented on pom.xml
> +			<artifactId>lombok-mapstruct-binding</artifactId>
Это чтобы работало аннотация mapping в bookingmapper и в других мапперах

2023-03-15 18:11 UTC, qwerty-yhn commented on pom.xml
> +			<artifactId>lombok-mapstruct-binding</artifactId>
Мне ребята говорят что так правильнее, ну и меньше кода писать

2023-03-15 18:13 UTC, qwerty-yhn commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                 @RequestParam(defaultValue = "ALL", required = false) String state) {
Чесно говоря не экперементировал, попробую)

2023-03-15 18:16 UTC, qwerty-yhn commented on src/main/java/ru/practicum/shareit/booking/BookingDtoOut.java
> +public class BookingDtoOut {
Вообще логика была такая что нам приходит я обозначил как BookingDtoIn а возвращает Out, типа вход выход)

2023-03-15 18:17 UTC, qwerty-yhn commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                     @NotEmpty @RequestHeader("X-Sharer-User-Id") Long userId) {
хорошо

2023-03-16 06:57 UTC, qwerty-yhn commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                 @RequestParam(defaultValue = "ALL", required = false) String state) {
Создал класс enum BookingState но смотри а как быть с состоянием UnsupportState? Если что прилетит не верное, отработает не верно

2023-03-16 06:59 UTC, qwerty-yhn commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +@Service
убрал

2023-03-16 07:13 UTC, qwerty-yhn commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            throw new NotFoundException("");
Ой... я забыл проэто)) я так и хотел сделать, хотел хранить локальные исключение в папке exeption)

2023-03-16 07:53 UTC, qwerty-yhn commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        userService.getUser(userId);
Создал функцию checkExist)

2023-03-16 08:17 UTC, qwerty-yhn commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            throw new NotFoundException("");
Поправил

2023-03-16 11:51 UTC, qwerty-yhn commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            throw new BadRequestException("");
ок

2023-03-16 11:51 UTC, qwerty-yhn commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            throw new BadRequestException("");
ок

2023-03-16 11:52 UTC, qwerty-yhn commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            throw new NotFoundException("");
ок

2023-03-16 11:52 UTC, qwerty-yhn commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            throw new BadRequestException("");
ок

2023-03-16 11:55 UTC, qwerty-yhn commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            throw new BadRequestException("");
ок

2023-03-16 12:00 UTC, qwerty-yhn commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            throw new NotFoundException("");
ок

2023-03-16 12:20 UTC, qwerty-yhn commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                .orElseThrow(() -> new NotFoundException("" + bookingId));
ок

2023-03-16 12:20 UTC, qwerty-yhn commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                throw new UnsupportedState(state);
Изначально так и задумывалось)

2023-03-16 12:23 UTC, qwerty-yhn commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +@Service
ок

2023-03-16 12:24 UTC, qwerty-yhn commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        return null;
Это от старой ветки осталось) Убрал

2023-03-16 12:37 UTC, qwerty-yhn commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            throw new NotFoundException(" not valid Owner(" + idOwner + ") of object");
ок

2023-03-16 12:42 UTC, qwerty-yhn commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        return itemRepository.findById(idItem).orElseThrow(() -> new NotFoundException("Not found item = " + idItem));
ок

2023-03-16 12:45 UTC, qwerty-yhn commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            throw new BadRequestException("");
ок

2023-03-16 12:46 UTC, qwerty-yhn commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +@Service
ок

2023-03-16 12:49 UTC, qwerty-yhn commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        List<User> usersTemp = getAllUsers();
мои эксперименты)) убрал

2023-03-16 12:50 UTC, qwerty-yhn commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +//        List<User> usersTemp = getAllUsers();
убрал

2023-03-16 12:57 UTC, qwerty-yhn commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        User user = repository.findById(id).orElseThrow(() -> new NotFoundException(""));
ок

2023-03-16 13:02 UTC, qwerty-yhn commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +//    private void checkExist(User user) {
Это от старой ветки осталось, честно говоря не нашел где применить, так как в тестах не требовалось ну я ее и под нож)) убрал

2023-03-16 13:21 UTC, qwerty-yhn commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +    private User updateParameters(User user) {
Тест такой: если в базе уже есть пользователь например с полями name=ivan и mail = ivan@com, а запрос приходит name=ivan mail=null, и что бы user не стал name = ivan mail = null; нужно из базы выгрузить предыдущее поле mail и записать и снова в базу). Если мое мнение то это все надо делать на запросах sql, потому что это не правильное расходование ресурсов сервера, а если пользователей сильно много то все?!   Сам я просто работаю с МК(микроконтроллеры) а там вопрос ресурсов стоит очень жестко.

2023-03-16 13:55 UTC, qwerty-yhn commented
Проблема не решилась, я просто пошел по другому пути. Какая была проблема: когда пишешь запросы @query() кастомные запросы, легкие запросы я смог сделать без проблем, а когда пошли посложнее я не понял как их дебажить, тоесть каждый раз запускать все тесты потом что  то менять в sql, мне показалось это очень долгим процессом а время шло. и в какой то момент я что то сделал с проектом и он перестал запускаться. и сообственно пришлось заново писать)

2023-03-17 18:47 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +    private User updateParameters(User user) {
Верная мысль, надо переработать бы, вытаскивать все из БД это точно некорректно

2023-03-17 18:47 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingDtoOut.java
> +public class BookingDtoOut {
лучше Request Response использовать

2023-03-17 18:47 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                 @RequestParam(defaultValue = "ALL", required = false) String state) {
ну разве это не проблемы пославшего?

2023-03-17 18:48 UTC, krylov-sergey-sergeevich approved these changes
Привет, гораздо лучше - зачет!

Давай метод который можно оптимизировать и не доставать все из бд про него подумаем и на пути к следующему дз проработаем.

2023-03-28 17:36 UTC, merged