Add item requests
qwerty-yhn/java-shareit pull request #3
Opened 2023-03-28 17:34 UTC by qwerty-yhn

2023-03-28 17:56 UTC, qwerty-yhn commented
Сергей привет!))) Я думал что предыдущий спринт долгий, но как я ошибался. Тесты написал но они такие, не очень, просто писать тесты когда готово приложение ну такое, я не помню логику работы) в моем видении тесты пишутся параллельно с основным кодом. Ну что слепил, устал ужас как и еще жесткий дедлайн на носу

2023-03-29 07:36 UTC, krylov-sergey-sergeevich requested changes
Привет, в целом очень неплохо

- Рекомендую коммиты делать более осознанными =) Они помогают в будущем вспоминать что сделано было
- Поправить мелочи которые отметил
- На счет тестов, в целом неплохо, но можно добавить где только verify еще assert что то если получится


p.s согласен что долгая домашка, на счет того что не помнишь - это тебе показательный пример. Я в свое время так же попался и с тех пор стараюсь писать комментарий на весь код который пишу или задеваю(чужой) тк спустя месяц при ежедневной разработке ты не помнишь абсолютно ничего что писал где-то)

2023-03-29 07:36 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            throw new BookingOfItemNotFoundException();
айди не скажем?

2023-03-29 07:36 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        LocalDateTime now = LocalDateTime.now();
Давай создадим класс DateUtils и будем создавать объекты времени через него, это позволит унифицировать способ получения времени и если будут правки делать их в 1 месте.

DateUtils.now()

2023-03-29 07:36 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/request/mapping/RequestMapper.java
> +public class RequestMapper {
Лучше сделать класс компонентом и использовать как бин

2023-03-29 07:36 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +class UserServiceImpl implements UserService {
съехал стиль

2023-03-29 07:36 UTC, krylov-sergey-sergeevich commented on src/test/java/ru/practicum/shareit/error/ErrorHandlerTest.java
> +public class ErrorHandlerTest {
?)

2023-03-29 14:26 UTC, qwerty-yhn commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            throw new BookingOfItemNotFoundException();
поправил)

2023-03-29 14:40 UTC, qwerty-yhn commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        LocalDateTime now = LocalDateTime.now();
поправил)

2023-03-29 14:41 UTC, qwerty-yhn commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +class UserServiceImpl implements UserService {
поправил)

2023-03-29 14:49 UTC, qwerty-yhn commented on src/main/java/ru/practicum/shareit/request/mapping/RequestMapper.java
> +public class RequestMapper {
Поправил)

2023-03-29 14:52 UTC, qwerty-yhn commented on src/test/java/ru/practicum/shareit/error/ErrorHandlerTest.java
> +public class ErrorHandlerTest {
Я наверное что то хотел написать и не написал)

2023-03-30 05:59 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки, но если я не ошибаюсь мапперы стали бинами но используются по старинке при помощи статик методов без inject =)

Это не критично, но давай по пути к 16 дз поправим

2023-04-05 16:48 UTC, merged